services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    container_name: db-postgres
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    networks:
      - private

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-nestjs
    volumes:
      - ./backend/:/backend/
    environment:
      - APP_PORT=${BACKEND_PORT}
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}?schema=public
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_TOKEN_KEY=${JWT_REFRESH_TOKEN_KEY}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    command: npm run docker:start:${ENV}
    depends_on:
      - db
    networks:
      - public
      - private

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - ENV=${ENV:-dev}
        - BACKEND_API_URL=${BACKEND_PROTOCOL:-http}://${BACKEND_HOST}:${BACKEND_PORT}
        - NEXTAUTH_SECRET=${JWT_SECRET_KEY}
        - NEXTAUTH_URL=http://localhost:${FRONTEND_PORT}/api/auth
    container_name: frontend-nextjs
    volumes:
      - ./frontend/:/frontend/
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    command: npm run docker:start:${ENV:-dev} -- -p ${FRONTEND_PORT}
    depends_on:
      - backend
    networks:
      - public

networks:
  public:
  private: